#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define XDIR 0
#define YDIR 1
#define ZDIR 2

#define fourbythree 1.3333333333
#define half 0.5
#define PI 3.141592654
#define three 3.0
#define two 2.0
#define oneval 1.0
#define four 4.0
#define twobyfive 0.4
#define fourth 0.25
#define eighth 0.125
#define zeroval 0.0
#define TINYVAL 1e-20
#define BIGVAL 1e20

#define NUM_MACRO_STATES 4
#define RHO_INDEX 0
#define VELX_INDEX 1
#define VELY_INDEX 2
#define VELZ_INDEX 3

#define NUM_MICRO_STATES 27

#define XX 0
#define XY 1
#define XZ 2
#define YY 3
#define YZ 4
#define ZZ 5

#define BC_PERIODIC 0
#define BC_NOSLIPWALL 1
#define BC_SLIPWALL 2
#define BC_OUTFLOW 3

#endif
